GET / HTTP/1.1
Host: localhost:3000
content-type: application/json


###
#Wrong parameters test
POST /insertUser HTTP/1.1
Host: localhost:3000
content-type: application/json

{
    "fullName": "Some user",
    "documentNumber": "098.890.989-89",
    "motherName": "Teste",
    "birthDate": "04/04/2000"
}